#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# Check if the number of arguments is correct
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file to the user home directory on the server
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~"
