#!/usr/bin/env bash
# Install the load balanecer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo 'ENABLED=1' >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << CONFIG
frontend front
        bind *:80
        mode http
        default_backend back
backend back
    balance roundrobin
    server 1564-web-01 54.157.173.128:80 check
    server 1564-web-02 34.229.161.133:80 check
CONFIG
sudo service haproxy restart
