#!/usr/bin/env bash
# Bash script with the minimum number of commands to ensure
# Ubuntu container’s Nginx installation listens to port 80

# remove default file in nginx
rm   /etc/nginx/sites-enabled/default

# create a symbolic link
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart
service nginx restart
