#!/usr/bin/env bash
# bash script that displays numbers from 1 to 100
# FizzBuzz

for i in $(seq 1 100); do
  if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
    echo -e "FizzBuzz"
  elif [ $((i % 3)) -eq 0 ]; then
    echo -e "Fizz"
  elif [ $((i % 5)) -eq 0 ]; then
    echo -e "Buzz"
  else
    echo "$i"
  fi
done
