#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while if, elif and else staements

i=0

while [ $i -lt 10 ];
do
	if [ $i -eq 3 ];
	then
		echo  "bad luck"
	elif [ $i -eq 7 ];
	then
		echo "good luck"
	fi

	echo "Best School"
	
	(( i++ ))
done
