#!/usr/bin/env bash
#  configure Nginx to serve your page from the route /airbnb-onepage/
server {
        listen 80;
        listen [::]:80;

        server_name 54.197.64.149;

        add_header X-Served-By 495755-web-01;

        location = /airbnb-onepage/ {
             proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }

        error_page 404 /404.html;
        location /404 {
          root /var/www/html;
          internal;
        }
}
