#!/usr/bin/env bash
# serve AirBnB_clone_v4
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name 54.197.64.149

        add_header X-Served-By 495755-web-01;

        location = /airbnb-onepage/ {
             proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }

        location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
             proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
        }

        location /api {
             proxy_pass http://127.0.0.1:5002/api;
        }

        # configure Airbnb_clone_4
        location / {
             proxy_pass http://127.0.0.1:5003/2-hbnb;
        }
        location /static {
             proxy_pass http://127.0.0.1:5003;
        }

        error_page 404 /404.html;
        location /404 {
             root /var/www/html;
             internal;
        }
}
